# Array and List

In [28]:
import numpy as np

In [ ]:
lst=list(range(1,25))
print(type(lst))
arr=np.array(lst)
print(arr)
print(type(arr))

<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
<class 'numpy.ndarray'>


In [ ]:
# Creating NumPy ARRAY

arr=np.array([1,2,3,4]
arr


[1, 2, 3, 4]

In [ ]:
# Create Numpy List

lst=[1,2,3,4]
lst

# arange function

In [31]:
arr=np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# 2D Array

In [3]:
# create 2d array

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

# 3D Array

In [ ]:
# Create 3d array

arr=np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])