In [2]:
import numpy as np

# List To Array Conversion

In [ ]:
#array nu list wich convert kiya si
lst=list(range(1,25))
arr= np.array(lst)
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


# 1D-Array

In [6]:
#create np array
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

#Range function

In [ ]:
#array nu create krne vich range di sii bina range function k
arr=np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# 2D-Array

In [ ]:
#2-D array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#3-D array
arr=np.array([[[1,2,3],[3,4,5]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
])

print(array_3d)
print(array_3d.shape)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#to print 1 
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#equal linespace provide kre k liye
arr= np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#dimension cntrl krne k liye
arr= np.linspace(1,10,5).reshape(5,1)#(start,end,row)    (row,column)
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [ ]:
arr=np.arange(0,30)
arr
arr.reshape(5,2,3)# (no. of matrices, rows, columns)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [44]:
arr.shape#check shape

(30,)

In [ ]:
#random initialisation
arr=np.random.randint(1,5,9)#(lower limit , upper limit, no. of times it should be printed)
arr

array([3, 2, 1, 3, 3, 3, 3, 1, 2], dtype=int32)

In [51]:
arr=np.random.randint(1,5,(3,3,3))#(lower limit, upper limit,(dimensions) )
arr

array([[[2, 2, 2],
        [3, 2, 4],
        [4, 4, 1]],

       [[3, 3, 2],
        [2, 4, 3],
        [1, 1, 3]],

       [[4, 4, 4],
        [4, 4, 2],
        [1, 1, 1]]], dtype=int32)

In [ ]:
arr=np.random.random(10)#to print array with 10 random decimal elements in given range
arr

array([0.21522995, 0.84429802, 0.37647667, 0.27833285, 0.90905335,
       0.87541585, 0.26149721, 0.64103273, 0.99236175, 0.15283751])

In [55]:
arr=np.random.randint(10) #to print any one random elment int the given range
arr

8

In [73]:


arr = np.random.random(10)  # 1D array with 10 random elements
arr_3d = arr[:, np.newaxis, np.newaxis]  # Convert to 3D

print(arr_3d)


[[[0.47447153]]

 [[0.56066758]]

 [[0.0376798 ]]

 [[0.49967311]]

 [[0.40223573]]

 [[0.5113919 ]]

 [[0.02298192]]

 [[0.48859568]]

 [[0.52911169]]

 [[0.05608278]]]


In [74]:


arr = np.random.random(10)  # 1D array with 10 random elements

arr_2d = arr[:, np.newaxis]  # Converts (10,) -> (10, 1)
print(arr_2d)



[[0.20822943]
 [0.00936449]
 [0.98416282]
 [0.1278054 ]
 [0.48802189]
 [0.43448893]
 [0.99856762]
 [0.49236904]
 [0.81311609]
 [0.94777671]]


In [76]:
arr=np.arange(60).reshape(10,6)
arr
arr.dtype#datatype
arr.ndim#dimension
arr.size#size
arr.shape


(10, 6)

In [ ]:
arr.flatten()#to convert any array into 1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [80]:
arr.ravel()#to convert any array in 1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
my_list=[[1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8]]
arr=np.array(my_list)
arr.shape#to show the shape


(2, 9)

In [105]:
arr.T.shape# to transpose
arr.T

array([[1, 0],
       [2, 1],
       [3, 2],
       [4, 3],
       [5, 4],
       [6, 5],
       [7, 6],
       [8, 7],
       [9, 8]])