# PANDAS

#pip install pandas

In [1219]:
import pandas as pd
import joblib as jl

In [1220]:
ub=pd.read_csv("Used_Bikes.csv") # Reads csv file and store it in ub variable

In [1221]:
ub # coloumns like bike_name,price,city,kms_driven are called as Features in ML

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [1222]:
ub.head(7) # prints first 5 rows

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
5                      Yamaha FZs 150cc   53499.0      Delhi     25000.0   
6         Honda CB Hornet 160R  ABS DLX   85000.0      Delhi      8200.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha  
5  First Owner  6.0  150.0         Yamaha  
6  First Owner  3.0  160.0          Honda

In [1223]:
ub.tail(7) # prints last 5 rows

bike_name    price         city  kms_driven  \
32641        Bajaj Avenger 220cc  41000.0        Delhi     20245.0   
32642         Hero Passion 100cc  15000.0  Perumbavoor     35000.0   
32643     Hero Passion Pro 100cc  39000.0        Delhi     22000.0   
32644       TVS Apache RTR 180cc  30000.0       Karnal      6639.0   
32645   Bajaj Avenger Street 220  60000.0        Delhi     20373.0   
32646  Hero Super Splendor 125cc  15600.0       Jaipur     84186.0   
32647         Bajaj Pulsar 150cc  22000.0         Pune     60857.0   

              owner   age  power  brand  
32641  Second Owner  11.0  220.0  Bajaj  
32642  Second Owner  19.0  100.0   Hero  
32643   First Owner   4.0  100.0   Hero  
32644   First Owner   9.0  180.0    TVS  
32645   First Owner   6.0  220.0  Bajaj  
32646   First Owner  16.0  125.0   Hero  
32647   First Owner  13.0  150.0  Bajaj

In [1224]:
#print 2 coloumns without knowing the names of the columns
ub.iloc[:,0:2]

bike_name     price
0        TVS Star City Plus Dual Tone 110cc   35000.0
1               Royal Enfield Classic 350cc  119900.0
2                      Triumph Daytona 675R  600000.0
3                      TVS Apache RTR 180cc   65000.0
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0
...                                     ...       ...
32643                Hero Passion Pro 100cc   39000.0
32644                  TVS Apache RTR 180cc   30000.0
32645              Bajaj Avenger Street 220   60000.0
32646             Hero Super Splendor 125cc   15600.0
32647                    Bajaj Pulsar 150cc   22000.0

[32648 rows x 2 columns]

In [1225]:
ub.info() # gives information about the dataset 
          # object datatype means string

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   32648 non-null  object 
 1   price       32648 non-null  float64
 2   city        32648 non-null  object 
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object 
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object 
dtypes: float64(4), object(4)
memory usage: 2.0+ MB


In [1226]:
ub.describe() # gives statistical information about the dataset

price     kms_driven           age         power
count  3.264800e+04   32648.000000  32648.000000  32648.000000
mean   6.829542e+04   26344.625184      8.048211    213.511302
std    9.071860e+04   22208.527695      4.031700    134.428868
min    4.400000e+03       1.000000      1.000000    100.000000
25%    2.500000e+04   12000.000000      5.000000    150.000000
50%    4.300000e+04   20373.000000      7.000000    150.000000
75%    8.000000e+04   35000.000000     10.000000    220.000000
max    1.900000e+06  750000.000000     63.000000   1800.000000

In [1227]:
ub.dtypes # gives datatype of each coloumn

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [1228]:
ub.shape # gives number of rows and coloumns

(32648, 8)

In [1229]:
# print(ub['bike_name']) # prints the bike_name coloumn
ub['city'] # prints the city coloumn

0        Ahmedabad
1            Delhi
2            Delhi
3        Bangalore
4        Bangalore
           ...    
32643        Delhi
32644       Karnal
32645        Delhi
32646       Jaipur
32647         Pune
Name: city, Length: 32648, dtype: object

In [1230]:
brand_name_ub = ub['brand'] # prints the brand coloumn
brand_name_ub

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...      
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: object

In [1231]:
brand_name_ub.unique() # prints the unique values

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [1232]:
brand_name_ub.nunique() # gives the how many number of unique values are there

23

In [1233]:
ub['bike_name'].nunique() # prints the number of unique values in the bike_name coloumn

471

In [1234]:
ub.loc[0:5] # prints the 0 to 5 rows of the dataframe

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
5                      Yamaha FZs 150cc   53499.0      Delhi     25000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha  
5  First Owner  6.0  150.0         Yamaha

In [1235]:
ub.iloc[0:5,0:3] # prints the first 5 rows and first 3 coloumns

bike_name     price       city
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad
1           Royal Enfield Classic 350cc  119900.0      Delhi
2                  Triumph Daytona 675R  600000.0      Delhi
3                  TVS Apache RTR 180cc   65000.0  Bangalore
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore

In [1236]:
ub.isnull() # prints the number of null values in each coloumn

bike_name  price   city  kms_driven  owner    age  power  brand
0          False  False  False       False  False  False  False  False
1          False  False  False       False  False  False  False  False
2          False  False  False       False  False  False  False  False
3          False  False  False       False  False  False  False  False
4          False  False  False       False  False  False  False  False
...          ...    ...    ...         ...    ...    ...    ...    ...
32643      False  False  False       False  False  False  False  False
32644      False  False  False       False  False  False  False  False
32645      False  False  False       False  False  False  False  False
32646      False  False  False       False  False  False  False  False
32647      False  False  False       False  False  False  False  False

[32648 rows x 8 columns]

In [1237]:
ub.isnull().sum() # prints the number of null values in each coloumn

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [1238]:
ub.duplicated().sum() # prints the number of duplicate rows

np.int64(25324)

In [1239]:
ub.drop_duplicates() # drops the duplicate rows and store it in dub variable

bike_name     price       city  kms_driven  \
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0      Delhi       110.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                    ...       ...        ...         ...   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi     48587.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore     60000.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur      3430.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0   
9372              Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0   

            owner  age  power            brand  
0     First Owner  3.0  110.0              TVS  
1     First Owner  4.0  350.0    Royal Enfield  
2     First Owner  8.0  675.0          Triumph  
3     First Owner  4.0  180.0              TVS  
4     First Owner  3.0  150.0           Yamaha  
...           ...  ...    ...              ...  
9362  First Owner  8.0  150.0             Hero  
9369  First Owner  9.0  220.0            Bajaj  
9370  First Owner  4.0  750.0  Harley-Davidson  
9371  First Owner  4.0  400.0            Bajaj  
9372  First Owner  5.0  220.0            Bajaj  

[7324 rows x 8 columns]

In [1240]:
ub.duplicated().sum() # prints the number of duplicate rows

np.int64(25324)

In [1241]:
ub.drop_duplicates(
    inplace=True
)  # used to save the dataset without storing it into new variable

In [1242]:
ub.duplicated().sum()

np.int64(0)

In [1243]:
ub.dropna(inplace=True) # drops the null values

In [1244]:
ub.isnull().sum() # prints the number of null values in each coloumn

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [1245]:
ub['bike_name'].duplicated().sum() # prints the number of duplicate values in the bike_name coloumn

np.int64(6853)

In [1246]:
ub['brand'].duplicated().sum() # prints the number of duplicate values in the brand coloumn

np.int64(7301)

In [1247]:
ub.fillna(0) # replace missing values with 0

bike_name     price       city  kms_driven  \
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0      Delhi       110.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                    ...       ...        ...         ...   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi     48587.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore     60000.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur      3430.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0   
9372              Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0   

            owner  age  power            brand  
0     First Owner  3.0  110.0              TVS  
1     First Owner  4.0  350.0    Royal Enfield  
2     First Owner  8.0  675.0          Triumph  
3     First Owner  4.0  180.0              TVS  
4     First Owner  3.0  150.0           Yamaha  
...           ...  ...    ...              ...  
9362  First Owner  8.0  150.0             Hero  
9369  First Owner  9.0  220.0            Bajaj  
9370  First Owner  4.0  750.0  Harley-Davidson  
9371  First Owner  4.0  400.0            Bajaj  
9372  First Owner  5.0  220.0            Bajaj  

[7324 rows x 8 columns]

In [1248]:
ub['price'].mean() # prints the mean of the price coloumn

np.float64(84883.90005461496)

In [1249]:
ub["price"].fillna(ub["price"].mean(),inplace=True) # replace missing values with mean of the price coloumn

C:\Users\Admin\AppData\Local\Temp\ipykernel_18156\3516204616.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ub["price"].fillna(ub["price"].mean(),inplace=True) # replace missing values with mean of the price coloumn


In [1250]:
ub.rename(columns={'kms_driven':'km_driven'},inplace=True) # rename column

In [1251]:
ub.columns

Index(['bike_name', 'price', 'city', 'km_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [1252]:
ub.head()

bike_name     price       city  km_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad    17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi    11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi      110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore    16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore    10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [1253]:
ub.sort_index(ascending=False) # sort the dataframe in descending order

bike_name     price       city  km_driven  \
9372              Bajaj Avenger Street 220   80000.0  Hyderabad     7127.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad    21300.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur     3430.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore    60000.0   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi    48587.0   
...                                    ...       ...        ...        ...   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore    10000.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore    16329.0   
2                     Triumph Daytona 675R  600000.0      Delhi      110.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi    11000.0   
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad    17654.0   

            owner  age  power            brand  
9372  First Owner  5.0  220.0            Bajaj  
9371  First Owner  4.0  400.0            Bajaj  
9370  First Owner  4.0  750.0  Harley-Davidson  
9369  First Owner  9.0  220.0            Bajaj  
9362  First Owner  8.0  150.0             Hero  
...           ...  ...    ...              ...  
4     First Owner  3.0  150.0           Yamaha  
3     First Owner  4.0  180.0              TVS  
2     First Owner  8.0  675.0          Triumph  
1     First Owner  4.0  350.0    Royal Enfield  
0     First Owner  3.0  110.0              TVS  

[7324 rows x 8 columns]

In [1254]:
ub.info() # gives information about the dataset

<class 'pandas.core.frame.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   bike_name  7324 non-null   object 
 1   price      7324 non-null   float64
 2   city       7324 non-null   object 
 3   km_driven  7324 non-null   float64
 4   owner      7324 non-null   object 
 5   age        7324 non-null   float64
 6   power      7324 non-null   float64
 7   brand      7324 non-null   object 
dtypes: float64(4), object(4)
memory usage: 515.0+ KB


In [1255]:
char_coloumn=ub.select_dtypes(include=['object']) # prints the object datatype coloumns and store it in char_coloumn variable
char_coloumn

bike_name       city        owner  \
0       TVS Star City Plus Dual Tone 110cc  Ahmedabad  First Owner   
1              Royal Enfield Classic 350cc      Delhi  First Owner   
2                     Triumph Daytona 675R      Delhi  First Owner   
3                     TVS Apache RTR 180cc  Bangalore  First Owner   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore  First Owner   
...                                    ...        ...          ...   
9362             Hero Hunk Rear Disc 150cc      Delhi  First Owner   
9369                   Bajaj Avenger 220cc  Bangalore  First Owner   
9370        Harley-Davidson Street 750 ABS    Jodhpur  First Owner   
9371                 Bajaj Dominar 400 ABS  Hyderabad  First Owner   
9372              Bajaj Avenger Street 220  Hyderabad  First Owner   

                brand  
0                 TVS  
1       Royal Enfield  
2             Triumph  
3                 TVS  
4              Yamaha  
...               ...  
9362             Hero  
9369            Bajaj  
9370  Harley-Davidson  
9371            Bajaj  
9372            Bajaj  

[7324 rows x 4 columns]

In [1256]:
num_coloumn = ub.select_dtypes(exclude='object')  # prints the numeric datatype coloumns and store it in num_coloumn variable

In [1257]:
ub.head(0)

Empty DataFrame
Columns: [bike_name, price, city, km_driven, owner, age, power, brand]
Index: []

In [1258]:
# drop bike_name and city coloumn from the dataframe
ub.drop(['bike_name','city'],axis=1,inplace=True)


In [1259]:
ub

price  km_driven        owner  age  power            brand
0      35000.0    17654.0  First Owner  3.0  110.0              TVS
1     119900.0    11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0      110.0  First Owner  8.0  675.0          Triumph
3      65000.0    16329.0  First Owner  4.0  180.0              TVS
4      80000.0    10000.0  First Owner  3.0  150.0           Yamaha
...        ...        ...          ...  ...    ...              ...
9362   25000.0    48587.0  First Owner  8.0  150.0             Hero
9369   35000.0    60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0     3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0    21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0     7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [1260]:
ub['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [1261]:
d1 = {"First Owner": 1, "Second Owner": 2, "Third Owner": 3, "Fourth Owner Or More": 4}
ub["owner"] = ub["owner"].map(d1)

In [1262]:
ub['owner'].unique()

array([1, 2, 3, 4])

In [1263]:
ub.head(20)

price  km_driven  owner  age  power          brand
0    35000.0    17654.0      1  3.0  110.0            TVS
1   119900.0    11000.0      1  4.0  350.0  Royal Enfield
2   600000.0      110.0      1  8.0  675.0        Triumph
3    65000.0    16329.0      1  4.0  180.0            TVS
4    80000.0    10000.0      1  3.0  150.0         Yamaha
5    53499.0    25000.0      1  6.0  150.0         Yamaha
6    85000.0     8200.0      1  3.0  160.0          Honda
7    45000.0    12645.0      1  3.0  100.0           Hero
8   145000.0     9190.0      1  3.0  350.0  Royal Enfield
9    88000.0    19000.0      2  7.0  500.0  Royal Enfield
10   72000.0    20000.0      1  7.0  150.0         Yamaha
11   95000.0     9665.0      1  4.0  250.0         Yamaha
12   78000.0     9900.0      1  4.0  200.0          Bajaj
13   29499.0    20000.0      1  8.0  100.0          Bajaj
14   29900.0    20000.0      1  7.0  125.0          Bajaj
15   90000.0    11574.0      1  3.0  200.0          Bajaj
16  120000.0    23000.0      1  3.0  200.0          Bajaj
17   48000.0    24725.0      1  5.0  150.0         Suzuki
18  240000.0    15025.0      2  3.0  302.0        Benelli
22   46500.0     3500.0      1  2.0  110.0           Hero

In [1264]:
ub["brand"].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [1265]:
ub["brand"].nunique()

23

In [1266]:
d2 = {
    "TVS": 1,
    "Royal Enfield": 2,
    "Triumph": 3,
    "Yamaha": 4,
    "Honda": 5,
    "Hero": 6,
    "Bajaj": 7,
    "Suzuki": 8,
    "Benelli": 9,
    "KTM": 10,
    "Mahindra": 11,
    "Kawasaki": 12,
    "Ducati": 13,
    "Hyosung": 14,
    "Harley-Davidson": 15,
    "Jawa": 16,
    "BMW": 17,
    "Indian": 18,
    "Rajdoot": 19,
    "LML": 20,
    "Yezdi": 21,
    "MV": 22,
    "Ideal": 23,
}
ub["brand"] = ub["brand"].map(d2)
ub["brand"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [1267]:
ub.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   price      7324 non-null   float64
 1   km_driven  7324 non-null   float64
 2   owner      7324 non-null   int64  
 3   age        7324 non-null   float64
 4   power      7324 non-null   float64
 5   brand      7324 non-null   int64  
dtypes: float64(4), int64(2)
memory usage: 400.5 KB


In [1268]:
ub

price  km_driven  owner  age  power  brand
0      35000.0    17654.0      1  3.0  110.0      1
1     119900.0    11000.0      1  4.0  350.0      2
2     600000.0      110.0      1  8.0  675.0      3
3      65000.0    16329.0      1  4.0  180.0      1
4      80000.0    10000.0      1  3.0  150.0      4
...        ...        ...    ...  ...    ...    ...
9362   25000.0    48587.0      1  8.0  150.0      6
9369   35000.0    60000.0      1  9.0  220.0      7
9370  450000.0     3430.0      1  4.0  750.0     15
9371  139000.0    21300.0      1  4.0  400.0      7
9372   80000.0     7127.0      1  5.0  220.0      7

[7324 rows x 6 columns]

In [1269]:
# encoding classes to numbers
# label onehot
# label encoding

In [1270]:
#pip install scikit-learn

In [1271]:
import sklearn

In [1272]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [1273]:
encoder = LabelEncoder()

In [1274]:
output = encoder.fit_transform(ub['brand'])

In [1275]:
output.__class__

numpy.ndarray

In [1276]:
output.shape

(7324,)

In [1277]:
output

array([ 0,  1,  2, ..., 14,  6,  6], shape=(7324,))

In [1278]:
ub["brand"] = output

In [1279]:
ub

price  km_driven  owner  age  power  brand
0      35000.0    17654.0      1  3.0  110.0      0
1     119900.0    11000.0      1  4.0  350.0      1
2     600000.0      110.0      1  8.0  675.0      2
3      65000.0    16329.0      1  4.0  180.0      0
4      80000.0    10000.0      1  3.0  150.0      3
...        ...        ...    ...  ...    ...    ...
9362   25000.0    48587.0      1  8.0  150.0      5
9369   35000.0    60000.0      1  9.0  220.0      6
9370  450000.0     3430.0      1  4.0  750.0     14
9371  139000.0    21300.0      1  4.0  400.0      6
9372   80000.0     7127.0      1  5.0  220.0      6

[7324 rows x 6 columns]

In [1280]:
ub.dtypes

price        float64
km_driven    float64
owner          int64
age          float64
power        float64
brand          int64
dtype: object

classify dependent and independent var

In [1281]:
x = ub.drop(["price"], axis=1)
y = ub[["price"]]
y  # dependent

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [1282]:
x  # independent var

km_driven  owner  age  power  brand
0       17654.0      1  3.0  110.0      0
1       11000.0      1  4.0  350.0      1
2         110.0      1  8.0  675.0      2
3       16329.0      1  4.0  180.0      0
4       10000.0      1  3.0  150.0      3
...         ...    ...  ...    ...    ...
9362    48587.0      1  8.0  150.0      5
9369    60000.0      1  9.0  220.0      6
9370     3430.0      1  4.0  750.0     14
9371    21300.0      1  4.0  400.0      6
9372     7127.0      1  5.0  220.0      6

[7324 rows x 5 columns]

now split dataset into trainig and testing data

In [1283]:
from sklearn.model_selection import train_test_split


In [1284]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)  # testsize how much data u want to keep for testing

In [1285]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

In [1286]:
x_train.head()
x_train.shape

(5859, 5)

In [1287]:
y_train.head()
y_train.shape

(5859, 1)

In [1288]:
x_test

km_driven  owner   age  power  brand
4909    22500.0      1   6.0  350.0      1
1942     3198.0      1   5.0  500.0      1
5763    15000.0      1   6.0  220.0      6
4800    27000.0      1  12.0  150.0      3
7614    16764.0      1   9.0  100.0      5
...         ...    ...   ...    ...    ...
5653    16523.0      1   5.0  750.0     14
609      2881.0      1   7.0  250.0     13
4211    23833.0      1   4.0  150.0      7
6379     9282.0      1   7.0  500.0      1
647      2980.0      1   6.0  160.0      0

[1465 rows x 5 columns]

In [1289]:
y_test

price
4909   88400.0
1942  102850.0
5763   67000.0
4800   30000.0
7614   20000.0
...        ...
5653  395000.0
609   140000.0
4211   54500.0
6379  114000.0
647    36000.0

[1465 rows x 1 columns]

# linear regresion

In [1290]:
from sklearn.linear_model import LinearRegression
import math
import numpy as np

In [1291]:
# obj
lr = LinearRegression()

In [1292]:
lr.fit(x_train, y_train)

LinearRegression()

In [1293]:
print("training score :-", lr.score(x_train, y_train))

training score :- 0.7053826605671762


In [1294]:
print("testing score :-", lr.score(x_test, y_test))

testing score :- 0.7586900869386206


In [1295]:
pred  = lr.predict(x_test)

In [1296]:
pred

array([[125382.54523531],
       [216422.20333617],
       [ 96966.48595241],
       ...,
       [ 72233.83615101],
       [208856.67620686],
       [  9305.60087569]], shape=(1465, 1))

In [1297]:
x_test.shape

(1465, 5)

In [1298]:
# y_test['pred']=pred.ravel()

In [1299]:
y_test

price
4909   88400.0
1942  102850.0
5763   67000.0
4800   30000.0
7614   20000.0
...        ...
5653  395000.0
609   140000.0
4211   54500.0
6379  114000.0
647    36000.0

[1465 rows x 1 columns]

# Loss Function
* MSE
* MAE
* HUBBER LOSS
* RMSE

In [1300]:
pred = lr.predict(x_test)
pred, y_test

(array([[125382.54523531],
        [216422.20333617],
        [ 96966.48595241],
        ...,
        [ 72233.83615101],
        [208856.67620686],
        [  9305.60087569]], shape=(1465, 1)),
          price
 4909   88400.0
 1942  102850.0
 5763   67000.0
 4800   30000.0
 7614   20000.0
 ...        ...
 5653  395000.0
 609   140000.0
 4211   54500.0
 6379  114000.0
 647    36000.0
 
 [1465 rows x 1 columns])

In [1301]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

MSE

In [1302]:
print("mean_squared_error: ",mean_squared_error(y_test, pred))

mean_squared_error:  4697994405.450049


MAE

In [1303]:
print("mean_absolute_error: ",mean_absolute_error(y_test, pred))

mean_absolute_error:  34658.30986561034


RMSE

In [1304]:
print("r2_score: ",r2_score(y_test, pred))

r2_score:  0.7586900869386206


In [1305]:
# by using math lib
print("by using math: ", )

by using math: 


In [1306]:
print("by using numpy: ", np.sqrt(mean_squared_error(y_test, pred)))

by using numpy:  68541.91714162983


Hubber Loss

In [1307]:
print("Hubber loss: ", )

Hubber loss: 


# Model Evaluation

Confusion Metrix

In [1308]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

In [1309]:
pred = (pred>0.5).astype(int).ravel()

In [1310]:
y_test = (y_test > 0.5).astype(int)

In [1311]:
y_test

price
4909      1
1942      1
5763      1
4800      1
7614      1
...     ...
5653      1
609       1
4211      1
6379      1
647       1

[1465 rows x 1 columns]

In [1312]:
pred

array([1, 1, 1, ..., 1, 1, 1], shape=(1465,))

In [1313]:
# confusion_metrix = pd.crosstab(y_test, pred)

In [1314]:
from sklearn.metrics import confusion_matrix as sklearn_confusion_matrix

# Use the sklearn confusion_matrix function
conf_matrix = sklearn_confusion_matrix(y_test, pred)
print(conf_matrix)

[[   0    0]
 [ 101 1364]]
